# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build-backend:

    runs-on: ubuntu-latest

    container: node:12.18.4

    services:
      redis:
        image: redis:6.0-alpine

    steps:
      - name: Descargar el código
        uses: actions/checkout@v2
      - name: Instalar las dependencias
        run: npm install
        working-directory: ./backend
      - name: Ejecutar los tests
        run: npm test -- --coverage
        working-directory: ./backend

  publish-backend:
    runs-on: ubuntu-latest

    needs: build-backend

    steps:
      - name: Descargar el código
        uses: actions/checkout@v2
      - name: Deploy en Heroku
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "github-actions-example-nodejs"
          heroku_email: "lszikora@dblandit.com"
          appdir: ./backend