# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Contador.js CI - Docker manual

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish-backend-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v2
      - name: Loguearse en DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Construir la imagen Docker
        run: docker build -t backend .
        working-directory: ./backend
      - name: Taguear la imagen
        run: docker tag backend ${{ secrets.DOCKER_USER }}/backend:latest
      - name: Publicar la imagen
        run: docker push ${{ secrets.DOCKER_USER }}/backend:latest