# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-frontend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js utilizando versión 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Instalar las dependencias
        run: npm install
        working-directory: ./frontend
      - name: Configurar credenciales git
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin $remote_url
        env:
          user_name: 'lszikoradblandit'
          user_email: 'lszikora@dblandit.com'
          remote_url: ${{ secrets.REMOTE_URL }}
      - name: Desplegar la app en GH Pages
        run: |
          npm run clean
          npm run deploy
        working-directory: ./frontend